# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .goal import Goal
from .goalie import Goalie
from .match import Match
from .match_summary import MatchSummary
from .penalty import Penalty
from .player import Player
from .score import Score
from .team import Team
