# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Goal(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'type': 'str',
        'team': 'Team',
        'time': 'int',
        'scorer': 'str',
        'assists': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'team': 'team',
        'time': 'time',
        'scorer': 'scorer',
        'assists': 'assists'
    }

    def __init__(self, id=None, type=None, team=None, time=None, scorer=None, assists=None):
        """
        Goal - a model defined in Swagger
        """

        self._id = None
        self._type = None
        self._team = None
        self._time = None
        self._scorer = None
        self._assists = None
        self.discriminator = None

        if id is not None:
          self.id = id
        self.type = type
        self.team = team
        self.time = time
        self.scorer = scorer
        if assists is not None:
          self.assists = assists

    @property
    def id(self):
        """
        Gets the id of this Goal.

        :return: The id of this Goal.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Goal.

        :param id: The id of this Goal.
        :type: int
        """

        self._id = id

    @property
    def type(self):
        """
        Gets the type of this Goal.

        :return: The type of this Goal.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Goal.

        :param type: The type of this Goal.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["PR", "RS", "PO"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def team(self):
        """
        Gets the team of this Goal.

        :return: The team of this Goal.
        :rtype: Team
        """
        return self._team

    @team.setter
    def team(self, team):
        """
        Sets the team of this Goal.

        :param team: The team of this Goal.
        :type: Team
        """
        if team is None:
            raise ValueError("Invalid value for `team`, must not be `None`")

        self._team = team

    @property
    def time(self):
        """
        Gets the time of this Goal.
        Seconds left in the period when the goal was scored

        :return: The time of this Goal.
        :rtype: int
        """
        return self._time

    @time.setter
    def time(self, time):
        """
        Sets the time of this Goal.
        Seconds left in the period when the goal was scored

        :param time: The time of this Goal.
        :type: int
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")

        self._time = time

    @property
    def scorer(self):
        """
        Gets the scorer of this Goal.

        :return: The scorer of this Goal.
        :rtype: str
        """
        return self._scorer

    @scorer.setter
    def scorer(self, scorer):
        """
        Sets the scorer of this Goal.

        :param scorer: The scorer of this Goal.
        :type: str
        """
        if scorer is None:
            raise ValueError("Invalid value for `scorer`, must not be `None`")

        self._scorer = scorer

    @property
    def assists(self):
        """
        Gets the assists of this Goal.

        :return: The assists of this Goal.
        :rtype: list[str]
        """
        return self._assists

    @assists.setter
    def assists(self, assists):
        """
        Sets the assists of this Goal.

        :param assists: The assists of this Goal.
        :type: list[str]
        """

        self._assists = assists

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Goal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
