# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Goalie(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'number': 'int',
        'name': 'str',
        'team': 'Team',
        'shots': 'float',
        'saves': 'float'
    }

    attribute_map = {
        'id': 'id',
        'number': 'number',
        'name': 'name',
        'team': 'team',
        'shots': 'shots',
        'saves': 'saves'
    }

    def __init__(self, id=None, number=None, name=None, team=None, shots=None, saves=None):
        """
        Goalie - a model defined in Swagger
        """

        self._id = None
        self._number = None
        self._name = None
        self._team = None
        self._shots = None
        self._saves = None
        self.discriminator = None

        if id is not None:
          self.id = id
        self.number = number
        self.name = name
        self.team = team
        if shots is not None:
          self.shots = shots
        if saves is not None:
          self.saves = saves

    @property
    def id(self):
        """
        Gets the id of this Goalie.

        :return: The id of this Goalie.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Goalie.

        :param id: The id of this Goalie.
        :type: int
        """

        self._id = id

    @property
    def number(self):
        """
        Gets the number of this Goalie.
        The player's jersey number

        :return: The number of this Goalie.
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """
        Sets the number of this Goalie.
        The player's jersey number

        :param number: The number of this Goalie.
        :type: int
        """
        if number is None:
            raise ValueError("Invalid value for `number`, must not be `None`")

        self._number = number

    @property
    def name(self):
        """
        Gets the name of this Goalie.

        :return: The name of this Goalie.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Goalie.

        :param name: The name of this Goalie.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def team(self):
        """
        Gets the team of this Goalie.

        :return: The team of this Goalie.
        :rtype: Team
        """
        return self._team

    @team.setter
    def team(self, team):
        """
        Sets the team of this Goalie.

        :param team: The team of this Goalie.
        :type: Team
        """
        if team is None:
            raise ValueError("Invalid value for `team`, must not be `None`")

        self._team = team

    @property
    def shots(self):
        """
        Gets the shots of this Goalie.
        Number of shots faced

        :return: The shots of this Goalie.
        :rtype: float
        """
        return self._shots

    @shots.setter
    def shots(self, shots):
        """
        Sets the shots of this Goalie.
        Number of shots faced

        :param shots: The shots of this Goalie.
        :type: float
        """

        self._shots = shots

    @property
    def saves(self):
        """
        Gets the saves of this Goalie.
        Number of saves made

        :return: The saves of this Goalie.
        :rtype: float
        """
        return self._saves

    @saves.setter
    def saves(self, saves):
        """
        Sets the saves of this Goalie.
        Number of saves made

        :param saves: The saves of this Goalie.
        :type: float
        """

        self._saves = saves

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Goalie):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
