# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.penalties_api import PenaltiesApi


class TestPenaltiesApi(unittest.TestCase):
    """ PenaltiesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.penalties_api.PenaltiesApi()

    def tearDown(self):
        pass

    def test_penalties(self):
        """
        Test case for penalties

        All penalties for the season
        """
        pass

    def test_save_penalty(self):
        """
        Test case for save_penalty

        Save a penalty
        """
        pass


if __name__ == '__main__':
    unittest.main()
