# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.goalie import Goalie


class TestGoalie(unittest.TestCase):
    """ Goalie unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoalie(self):
        """
        Test Goalie
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.goalie.Goalie()
        pass


if __name__ == '__main__':
    unittest.main()
