# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.matches_api import MatchesApi


class TestMatchesApi(unittest.TestCase):
    """ MatchesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.matches_api.MatchesApi()

    def tearDown(self):
        pass

    def test_add_match(self):
        """
        Test case for add_match

        Add a new match
        """
        pass

    def test_find_match(self):
        """
        Test case for find_match

        Get a specific match
        """
        pass

    def test_find_team_schedule(self):
        """
        Test case for find_team_schedule

        Find this season's schedule for a given team
        """
        pass

    def test_match_summary(self):
        """
        Test case for match_summary

        Get a specific match
        """
        pass

    def test_save_match_summary(self):
        """
        Test case for save_match_summary

        Update the match summary
        """
        pass

    def test_season_matches(self):
        """
        Test case for season_matches

        Get the current season's matches
        """
        pass

    def test_update_match(self):
        """
        Test case for update_match

        Update an existing match
        """
        pass


if __name__ == '__main__':
    unittest.main()
