# coding: utf-8

"""
    SNC API

    This is an API server for the data scraped from the SNC website.

    OpenAPI spec version: 1.0.0
    Contact: not-an-email@example.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.goal import Goal
from .models.goalie import Goalie
from .models.match import Match
from .models.match_summary import MatchSummary
from .models.penalty import Penalty
from .models.player import Player
from .models.score import Score
from .models.team import Team

# import apis into sdk package
from .apis.goalies_api import GoaliesApi
from .apis.goals_api import GoalsApi
from .apis.matches_api import MatchesApi
from .apis.penalties_api import PenaltiesApi
from .apis.players_api import PlayersApi
from .apis.teams_api import TeamsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration
